services:
  db:
    image: postgres:16
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=money_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: compose.Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/rails s -b '0.0.0.0' -p 10000"
    volumes:
      - .:/rails
    ports:
      - "10000:10000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/money_development
      - REDIS_URL=redis://redis:6379/1
      - RAILS_MASTER_KEY
  redis:
    image: redis:7.0
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  bundle_data:
  redis_data:
